#!/bin/bash

# debian based apps

sudo apt-get install vlc chromium firefox neofetch cowsay zathura git xclip

# snap based apps

sudo apt install snapd
sudo snap install telegram-desktop
sudo snap install snap-store
sudo snap install --classic code 